# .goreleaser.yml
# Build customization
builds:
  - binary: visionlord-server
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
release:
  draft: true
snapshot:
  # Allows you to change the name of the generated snapshot
  # releases. The following variables are available:
  # - Commit
  # - Tag
  # - Timestamp
  # Default is `SNAPSHOT-{{.Commit}}`.
  name_template: SNAPSHOT-{{.Tag}}
